esphome:
  name: esphome-web-f44354
  friendly_name: esp-wroom-32
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "SJ0Imr2g55fz"

external_components:
  - source:
      type: git
      url: https://github.com/andreasgrontved/dfrobot_c1001_rep
      ref: main
    components: [dfrobot_c1001]

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200

dfrobot_c1001:
  id: dfrobot_sensor
  uart_id: uart_bus
  human_presence:
    name: "Human Presence"
    id: human_presence
  human_movement:
    name: "Human Movement"
    id: human_movement
  fall_state:
    name: "Fall State"
    id: fall_state
  residency_state:
    name: "Stationary Dwell"
    id: residency_state
